env:
    CIRRUS_CLONE_DEPTH: 
    BUILD_HOSTNAME: "cirrus-ci.org"
    token: ""
    chat_id: ""
    
task:
  name: "Test"
  timeout_in: 2h
  container:
      image: nexgang/ubuntu:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
