name: Run Cirrus Tasks

on:
  push:
    branches: [ 1 ]
  pull_request:
    branches: [ 1 ]

jobs:
  cirrus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cirruslabs/cirrus-action@v2
